[workspace]
resolver = "2"
members = [".", "reime"]

[package]
name = "miel"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
thiserror = "2.0.12"

ash = "0.38.0"
ash-window = "0.13.0"
winit = "0.30.9"
